<a href="https://colab.research.google.com/github/AbdurNawaz/Charc-RNN/blob/master/Charac_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import time
from collections import namedtuple
import numpy as np
import tensorflow as tf

In [0]:
with open('anna.txt') as f:
    text = f.read()
vocab = sorted(set(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

In [8]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

In [9]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70],
      dtype=int32)

In [0]:
def get_batches(arr, batch_size, n_steps):
  char_per_batch = batch_size*n_steps
  num_batches = len(arr)//char_per_batch

  arr = arr[:num_batches*char_per_batch]
  arr = arr.reshape((batch_size, -1))

  for i in range(0, arr.shape[1], n_steps):
    x = arr[:, i:i+n_steps]
    y_temp = arr[:, i+1:i+n_steps+1]

    y = np.zeros(x.shape, dtype=x.dtype)
    y[:, :y_temp.shape[1]] = y_temp

    yield x, y

In [36]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)
print('x\n', x[:, :10])
print('y\n', y[:, :10])

x
 [[31 64 57 72 76 61 74  1 16  0]
 [ 1 57 69  1 70 71 76  1 63 71]
 [78 65 70 13  0  0  3 53 61 75]
 [70  1 60 77 74 65 70 63  1 64]
 [ 1 65 76  1 65 75 11  1 75 65]
 [ 1 37 76  1 79 57 75  0 71 70]
 [64 61 70  1 59 71 69 61  1 62]
 [26  1 58 77 76  1 70 71 79  1]
 [76  1 65 75 70  7 76 13  1 48]
 [ 1 75 57 65 60  1 76 71  1 64]]
y
 [[64 57 72 76 61 74  1 16  0  0]
 [57 69  1 70 71 76  1 63 71 65]
 [65 70 13  0  0  3 53 61 75 11]
 [ 1 60 77 74 65 70 63  1 64 65]
 [65 76  1 65 75 11  1 75 65 74]
 [37 76  1 79 57 75  0 71 70 68]
 [61 70  1 59 71 69 61  1 62 71]
 [ 1 58 77 76  1 70 71 79  1 75]
 [ 1 65 75 70  7 76 13  1 48 64]
 [75 57 65 60  1 76 71  1 64 61]]


In [0]:
def build_inputs(batch_size, n_steps):
  inputs = tf.placeholder(tf.int32, [batch_size, n_steps], 'inputs')
  targets = tf.placeholder(tf.int32, [batch_size, n_steps], 'targets')

  keep_prob = tf.placeholder(tf.float32, name='keep_prob')

  return inputs, targets, keep_prob
